/*
* Proyecto_Reloj.asm
*
* Creado: 2/27/2026 4:30:42 PM
* Autor : Josue Eli Mata Ixcayau
* Descripci?n: Un reloj digital que permita mostrar hora y minutos, dias y meses, tambien programar una alarma a una hora especifica.
*/
/****************************************/
// Encabezado (Definici?n de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
.equ	TCNT1_value = 0xD8F0
/****************************************/
//	Variables en SRAM
.dseg						// VARIABLE DENTRO DE SRAM
MOD_MIN_U:		.byte   1   // VARIABLES DE MODIFICACION DE MINUTOS
MOD_MIN_D:		.byte   1
MOD_HORA_U:     .byte   1	// VARIABLES DE MODIFICACION DE HORAS
MOD_HORA_D:     .byte   1
MOD_DIA_U:		.byte	1	// VARIABLES DE MODIFICACION DE DIAS
MOD_DIA_D:		.byte	1
MOD_MES_U:		.byte	1	// VARIABLES DE MODIFICACION DE MESES
MOD_MES_D:		.byte	1
A_MIN_U:		.byte	1	// VARIABLES DE MINUTOS PARA ALARMA
A_MIN_D:		.byte	1	
A_HORA_U:		.byte	1	// VARIABLES DE HORAS PARA ALARMA
A_HORA_D:		.byte	1
/****************************************/
//	CODIGO
.cseg
.org	0x0000
	JMP	START
.org	PCI1addr
	JMP	ISR_PCI1
.org	OVF1addr
	JMP	ISR_TMR1_OVF
.org	OVF0addr
	JMP	ISR_TMR0_OVF
.def	VALOR_C_ANTERIOR =		R0
.def	S_PORT =				R1
.def	CONTADOR_MULTI =		R2
.def	MODO =					R3
.def	CONTADOR_MODO =			R4
.def	MAX_MODES =				R5
.def	CONTADOR_MESES =		R6
.def	VARIABLE_DIAS =			R7
.def	BANDERA_ACCION =		R8
.def	BANDERA_ESTADO =		R9
.def	VALOR_C_ACTUAL =		R10
.def	ENTRADA_PINC =			R13
.def	REG_DISPLAY =			R14
.def	S_DISPLAY =				R15
.def	CONTADOR_M_U =			R17
.def	CONTADOR_M_D =			R18
.def	CONTADOR_H_U =			R19
.def	CONTADOR_H_D =			R20
.def	CONTADOR_TIEMPO =		R21
.def	CONTADOR_D_U =			R22
.def	CONTADOR_D_D =			R23
.def	CONTADOR_MES_U =		R24		
.def	CONTADOR_MES_D =		R25		

START:
 /****************************************/
// Configuraci?n de la pila
	LDI     R16, LOW(RAMEND)
	OUT     SPL, R16
	LDI     R16, HIGH(RAMEND)
	OUT     SPH, R16
/****************************************/
// CREACION DE TABLA PARA DISPLAY
Numero: .db 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90, 0x88, 0x83, 0xF0, 0xA1, 0x86, 0x8E
Cantidad_dias:	.db	0x00, 0x1F, 0x1C, 0x1F, 0x1E, 0x1F, 0x1E, 0x1F, 0x1F, 0x1E, 0x1F, 0x1E, 0x1F, 0x00
/****************************************/
// Configuracion MCU
SETUP:
    CLI									// DESHABILITAR INTERRUPCIONES GLOBALES
	// PRESCALER
	LDI		R16,	(1 << CLKPCE)
	STS		CLKPR,	R16					// HABILITAR CAMBIOS EN CLOCK PRINCIPAL PARA HABILITAR PRESCALER
	LDI		R16,	(1 << CLKPS2)
	STS		CLKPR,	R16					// CAMBIAR FRECUENCIA DE 16 MHz a 1MHz

	// TIMER
	CALL INIT_TMR0
	CALL INIT_TMR1

    // ENTRADAS
	LDI		R16,	0x00			
	OUT		DDRC,	R16					// PONER EN ENTRADAS LOS BITS 0 Y 1 DE PORTC
	LDI		R16,	0xFF				// VALOR PARA ACTIVAR PULL UPS EN 0 Y 1
	OUT		PORTC,	R16					// HABILITAR PULL UPS EN PINC

	// SALIDAS
	LDI		R16,	0xFF			
	OUT		DDRB,	R16					// PONER EN SALIDAS LOS BITS DE PORTB
	OUT		DDRD,	R16					// PONER EN SALIDAS LOS BITS DE PORTD  

	LDI		R16,	0xFF
	OUT		PORTB,	R16					// PONER DE VALOR INICIAL PARA PORTB 0

		// DISPLAYS DE 7 SEGMENTOS
	LDI		ZL,		LOW(Numero<<1)		//
	LDI		ZH,		HIGH(Numero<<1)		//
	LPM		R16,	Z
	OUT		PORTD,	R16					// PONER DE VALOR INICIAL PARA PORTD 0

	// HABILITACION DE INTERRUPCIONES
	LDI		R16,	(1 << PCIE1)
    STS		PCICR,	R16					// HABILITA INTERRUPCIONES EN PORTC
    LDI		R16,	(1 << PCINT8) | (1 << PCINT9) | (1 << PCINT10) | (1 << PCINT11) | (1 << PCINT12)
    STS		PCMSK1, R16
	LDI		R16,	(1 << TOIE0)
	STS		TIMSK0,	R16
	LDI		R16,	(1 << TOIE1)
	STS		TIMSK1,	R16

	// VARIABLES A USAR
	IN		VALOR_C_ANTERIOR,	PINC		// VALORES DE PIN C
	LDI		R16,				0x00
	STS		MOD_MIN_U,			R16			// REINICIAR VALORES DE VARIABLES
	STS		MOD_MIN_D,			R16
	STS		MOD_HORA_U,			R16
	STS		MOD_HORA_D,			R16
	STS		MOD_DIA_D,			R16
	STS		MOD_MES_D,			R16
	MOV		CONTADOR_MULTI,		R16			// REINICIAR VALORES EN CONTADOR PARA MULTIPLEXADO
	LDI		R16,				0x01
	STS		MOD_DIA_U,			R16
	STS		MOD_MES_U,			R16
	MOV		CONTADOR_MESES,		R16
	LDI		R16,				5
	MOV		MAX_MODES,			R16
	CLR		CONTADOR_H_U					// REGISTRO DE CONTADOR
	CLR		CONTADOR_H_D					// REGISTRO DE CONTADOR
	CLR		CONTADOR_M_U					// CONTADOR DE UNIDADES PARA DISPLAY
	CLR		CONTADOR_M_D					// CONTADOR DE DECIMAS PARA DISPLAY
	CLR		CONTADOR_TIEMPO					// CONTADOR PARA TIEMPO
	CLR		REG_DISPLAY						// REGISTRO DONDE SE GUARDA VALOR QUE VA A SALIR A DISPLAY
	LDI		CONTADOR_D_U,		0x01					
	CLR		CONTADOR_D_D					
	LDI		CONTADOR_MES_U,		0x01					
	CLR		CONTADOR_MES_D
	CLR		CONTADOR_MESES
	CLR		BANDERA_ACCION
	CLR		BANDERA_ESTADO

	SEI									// HABILITAR INTERRUPCIONES GLOBALES
/****************************************/
// Loop Infinito
MAIN_LOOP:
	LDI		R16,	0
	CP		MODO,	R16
	BREQ	RELOJ
	LDI		R16,	1
	CP		MODO,	R16
	BREQ	FECHA
	LDI		R16,	2
	CP		MODO,	R16
	BREQ	MODIFICAR_RELOJ
	LDI		R16,	3
	CP		MODO,	R16
	BREQ	MODIFICAR_FECHA
	LDI		R16,	4
	CP		MODO,	R16
	BREQ	SET_ALARMA

RELOJ:
	LDI		R16,	0x01
	MOV		BANDERA_ESTADO,		R16
	CALL	SALIDA_DISPLAY_HORA
	RJMP	REGRESO_MAIN
FECHA:
	LDI		R16,	0x01
	MOV		BANDERA_ESTADO,		R16
	CALL	SALIDA_DISPLAY_FECHA
	RJMP	REGRESO_MAIN
MODIFICAR_RELOJ:
	LDI		R16,	0x02
	MOV		BANDERA_ESTADO,		R16
	CALL	CAMBIAR_RELOJ
	CALL	SALIDA_DISPLAY_HORA
	RJMP	REGRESO_MAIN
MODIFICAR_FECHA:
	LDI		R16,	0x02
	MOV		BANDERA_ESTADO,		R16
	CALL	CAMBIAR_FECHA
	CALL	SALIDA_DISPLAY_FECHA
	RJMP	REGRESO_MAIN
SET_ALARMA:
	LDI		R16,	0x02
	MOV		BANDERA_ESTADO,		R16
	CALL	SETEAR_ALARMA
	CALL	SALIDA_DISPLAY_HORA
	RJMP	REGRESO_MAIN
REGRESO_MAIN:
    RJMP    MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines
INIT_TMR0:
	LDI		R16,	(1 << CS01)			// CONFIGURANDO PRESCALER DE I/O A 8
	OUT		TCCR0B,	R16
	LDI		R16,	131					// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16					// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0
	RET

INIT_TMR1:
	LDI		R16,	0x00
	STS		TCCR1A,	R16
	LDI		R16,	(1 << CS10)
	STS		TCCR1B,	R16
	LDI		R16,	HIGH(TCNT1_value)
	STS		TCNT1H,	R16
	LDI		R16,	LOW(TCNT1_value)
	STS		TCNT1L,	R16
	RET

SALIDA_DISPLAY_HORA:
	CLR		S_DISPLAY
	OUT		PORTB,		S_PORT				// MANDAMOS REGISTRO A PORTB

	SBRC	S_PORT,	0						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_M_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	1						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_M_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY
	
	SBRC	S_PORT,	2						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_H_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	3						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_H_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY

	LDI		ZL,		LOW(Numero<<1)			// REINICIAMOS PUNTEROS
	LDI		ZH,		HIGH(Numero<<1)			//
	ADD		ZL,		REG_DISPLAY				// SUMAMOS A PARTE BAJA DE PUNTERO CONTADOR DE DISPLAY
	LPM		S_DISPLAY,	Z					// MANDAMOS VALOR DE Z A REGISTRO DE SALIDA
	OUT		PORTD,	S_DISPLAY
	RET

SALIDA_DISPLAY_FECHA:
	CLR		S_DISPLAY
	OUT		PORTB,		S_PORT				// MANDAMOS REGISTRO A PORTB

	SBRC	S_PORT,	0						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_MES_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	1						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_MES_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY
	
	SBRC	S_PORT,	2						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_D_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	3						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_D_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY

	LDI		ZL,		LOW(Numero<<1)			// REINICIAMOS PUNTEROS
	LDI		ZH,		HIGH(Numero<<1)			//
	ADD		ZL,		REG_DISPLAY				// SUMAMOS A PARTE BAJA DE PUNTERO CONTADOR DE DISPLAY
	LPM		S_DISPLAY,	Z					// MANDAMOS VALOR DE Z A REGISTRO DE SALIDA
	OUT		PORTD,	S_DISPLAY
	RET

CAMBIAR_RELOJ:
	IN		ENTRADA_PINC,		PINC				// SE LEE EL PIN C
	MOV		VALOR_C_ACTUAL,		ENTRADA_PINC		// MOVEMOS REGISTRO R16 A R5
	EOR		VALOR_C_ACTUAL,		VALOR_C_ANTERIOR	// XOR ENTRE VALORES ACTUALES Y VALORES ANTERIORES
	MOV		VALOR_C_ANTERIOR,	ENTRADA_PINC		// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES

	SBRC	VALOR_C_ACTUAL,		0					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_0
	SBRC	VALOR_C_ACTUAL,		1					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_1
	SBRC	VALOR_C_ACTUAL,		2					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_2
	SBRC	VALOR_C_ACTUAL,		3					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_3
	RET

CAMBIAR_FECHA:
	IN		ENTRADA_PINC,		PINC				// SE LEE EL PIN C
	MOV		VALOR_C_ACTUAL,		ENTRADA_PINC		// MOVEMOS REGISTRO R16 A R5
	EOR		VALOR_C_ACTUAL,		VALOR_C_ANTERIOR	// XOR ENTRE VALORES ACTUALES Y VALORES ANTERIORES
	MOV		VALOR_C_ANTERIOR,	ENTRADA_PINC		// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES

	SBRC	VALOR_C_ACTUAL,		0					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_0
	SBRC	VALOR_C_ACTUAL,		1					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_1
	SBRC	VALOR_C_ACTUAL,		2					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_2
	SBRC	VALOR_C_ACTUAL,		3					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_3
	RET

SETEAR_ALARMA:
	IN		ENTRADA_PINC,		PINC				// SE LEE EL PIN C
	MOV		VALOR_C_ACTUAL,		ENTRADA_PINC		// MOVEMOS REGISTRO R16 A R5
	EOR		VALOR_C_ACTUAL,		VALOR_C_ANTERIOR	// XOR ENTRE VALORES ACTUALES Y VALORES ANTERIORES
	MOV		VALOR_C_ANTERIOR,	ENTRADA_PINC		// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES

	SBRC	VALOR_C_ACTUAL,		0					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_0
	SBRC	VALOR_C_ACTUAL,		1					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_1
	SBRC	VALOR_C_ACTUAL,		2					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_2
	SBRC	VALOR_C_ACTUAL,		3					// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_3
	RET

BIT_0:
	LDI		R16,	0x01
	CP		BANDERA_ACCION,	R16
	BREQ	AU_HORA
	LDI		R16,	0x02
	CP		BANDERA_ACCION,	R16
	BREQ	AU_DIA
	LDI		R16,	0x04
	CP		BANDERA_ACCION,	R16
	BREQ	AU_HORA_ALARMA
AU_HORA:
	SBRS	ENTRADA_PINC,	0				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_HORA
	RJMP	SALIDA_BIT_0
AU_DIA:
	SBRS	ENTRADA_PINC,	0				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_DIA
	RJMP	SALIDA_BIT_0
AU_HORA_ALARMA:
	SBRS	ENTRADA_PINC,	0				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_HORA_ALARMA
	RJMP	SALIDA_BIT_0
SALIDA_BIT_0:
	RET

BIT_1:
	LDI		R16,	0x01
	CP		BANDERA_ACCION,	R16
	BREQ	DE_HORA
	LDI		R16,	0x02
	CP		BANDERA_ACCION,	R16
	BREQ	DE_DIA
	LDI		R16,	0x04
	CP		BANDERA_ACCION,	R16
	BREQ	DE_HORA_ALARMA
DE_HORA:
	SBRS	ENTRADA_PINC,	1				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_HORA
	RJMP	SALIDA_BIT_0
DE_DIA:
	SBRS	ENTRADA_PINC,	1				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_DIA
	RJMP	SALIDA_BIT_0
DE_HORA_ALARMA:
	SBRS	ENTRADA_PINC,	1				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_HORA_ALARMA
	RJMP	SALIDA_BIT_0
SALIDA_BIT_1:
	RET

BIT_2:
	LDI		R16,	0x01
	CP		BANDERA_ACCION,	R16
	BREQ	AU_MIN
	LDI		R16,	0x02
	CP		BANDERA_ACCION,	R16
	BREQ	AU_MES
	LDI		R16,	0x04
	CP		BANDERA_ACCION,	R16
	BREQ	AU_MIN_ALARMA
AU_MIN:
	SBRS	ENTRADA_PINC,	2				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_MIN
	RJMP	SALIDA_BIT_2
AU_MES:
	SBRS	ENTRADA_PINC,	2				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_MES
	RJMP	SALIDA_BIT_2
AU_MIN_ALARMA:
	SBRS	ENTRADA_PINC,	2				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO_MIN_ALARMA
	RJMP	SALIDA_BIT_2
SALIDA_BIT_2:
	RET

BIT_3:
	LDI		R16,	0x01
	CP		BANDERA_ACCION,	R16
	BREQ	DE_MIN
	LDI		R16,	0x02
	CP		BANDERA_ACCION,	R16
	BREQ	DE_MES
	LDI		R16,	0x04
	CP		BANDERA_ACCION,	R16
	BREQ	DE_MIN_ALARMA
DE_MIN:
	SBRS	ENTRADA_PINC,	3				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_MIN
	RJMP	SALIDA_BIT_3
DE_MES:
	SBRS	ENTRADA_PINC,	3				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_MES
	RJMP	SALIDA_BIT_3
DE_MIN_ALARMA:
	SBRS	ENTRADA_PINC,	3				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE_MIN_ALARMA
	RJMP	SALIDA_BIT_3
SALIDA_BIT_3:
	RET

AUMENTO_MIN:
	LDS		CONTADOR_M_U,	MOD_MIN_U
	LDS		CONTADOR_M_D,	MOD_MIN_D

	INC		CONTADOR_M_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_M_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_AUMENTO_MIN
	CLR		CONTADOR_M_U

	INC		CONTADOR_M_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_M_D,	0x06			// COMPARO CON 6
	BRNE	SALIDA_AUMENTO_MIN
	CLR		CONTADOR_M_D
SALIDA_AUMENTO_MIN:
	STS		MOD_MIN_U,	CONTADOR_M_U
	STS		MOD_MIN_D,	CONTADOR_M_D
	RET

AUMENTO_HORA:
	LDS		CONTADOR_H_U,	MOD_HORA_U
	LDS		CONTADOR_H_D,	MOD_HORA_D
	CPI		CONTADOR_H_D,	0x02
	BREQ	C_2_HORAS

	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_AUMENTO_HORA
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	C_D_HORAS

C_2_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x04			// COMPARO CON 4
	BRNE	SALIDA_AUMENTO_HORA
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	C_D_HORAS

C_D_HORAS:
	INC		CONTADOR_H_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_H_D,	0x03			// COMPARO CON 6
	BRNE	SALIDA_AUMENTO_HORA
	CLR		CONTADOR_H_D					// REINICIO CONTADOR DE DECENAS
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
SALIDA_AUMENTO_HORA:
	STS		MOD_HORA_U,	CONTADOR_H_U	
	STS		MOD_HORA_D,	CONTADOR_H_D				
	RET

AUMENTO_DIA:
	LDS		CONTADOR_D_U,	MOD_DIA_U
	LDS		CONTADOR_D_D,	MOD_DIA_D

	LDI		ZL,		LOW(Cantidad_dias<<1)	// REINICIAMOS PUNTEROS DIAS
	LDI		ZH,		HIGH(Cantidad_dias<<1)
	ADD		ZL,		CONTADOR_MESES
	LPM		VARIABLE_DIAS,	Z

	CPI		CONTADOR_D_D,	0x03
	BREQ	C_3_DIAS
	CPI		CONTADOR_D_D,	0x02
	BREQ	C_2_DIAS

	C_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 2
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_U
	RJMP	C_D_DIAS

	C_2_DIAS:
	LDI		R16,	28
	CP		VARIABLE_DIAS,	R16
	BREQ	C_2_FEBRERO_DIAS
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_U
	RJMP	C_D_DIAS
	C_2_FEBRERO_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x09			// COMPARO CON 9
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_U
	RJMP	C_D_DIAS

	C_3_DIAS:
	LDI		R16,	31
	CP		VARIABLE_DIAS,	R16
	BREQ	C_3_1_DIAS
	LDI		R16,	30
	CP		VARIABLE_DIAS,	R16
	BREQ	C_3_2_DIAS
	C_3_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x02			// COMPARO CON 2
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_U
	RJMP	C_D_DIAS
	C_3_2_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x01			// COMPARO CON 1
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_U
	RJMP	C_D_DIAS
	
	C_D_DIAS:
	INC		CONTADOR_D_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_D_D,	0x04			// COMPARO CON 4
	BRNE	SALIDA_AUMENTO_DIA
	CLR		CONTADOR_D_D
	LDI		CONTADOR_D_U,	0x01
SALIDA_AUMENTO_DIA:
	STS		MOD_DIA_U,	CONTADOR_D_U
	STS		MOD_DIA_D,	CONTADOR_D_D
	RET

AUMENTO_MES:
	LDS		CONTADOR_MES_U,	MOD_MES_U
	LDS		CONTADOR_MES_D,	MOD_MES_D
	CPI		CONTADOR_MES_D,	0x02
	BREQ	C_2_MESES

	C_1_MESES:
	INC		CONTADOR_MESES
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_AUMENTO_MES
	CLR		CONTADOR_MES_U	
	RJMP	CONTEO_D_MESES
	C_2_MESES:
	INC		CONTADOR_MESES
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x03			// COMPARO CON 2
	BRNE	SALIDA_AUMENTO_MES
	LDI		CONTADOR_MES_U,	0x01
	MOV		CONTADOR_MESES,	CONTADOR_MES_U
	RJMP	CONTEO_D_MESES

	C_D_MESES:
	INC		CONTADOR_MES_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_MES_D,	0x02			// COMPARO CON 2
	BRNE	SALIDA_AUMENTO_MES
	CLR		CONTADOR_MES_D
	LDI		CONTADOR_MES_U,	0x01
	SALIDA_AUMENTO_MES:
	STS		MOD_MES_U,	CONTADOR_MES_U
	STS		MOD_MES_D,	CONTADOR_MES_D
	RET

AUMENTO_MIN_ALARMA:
	LDS		CONTADOR_M_U,	MOD_MIN_U
	LDS		CONTADOR_M_D,	MOD_MIN_D

	INC		CONTADOR_M_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_M_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_ALARMA_AUMENTO_MIN
	CLR		CONTADOR_M_U

	INC		CONTADOR_M_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_M_D,	0x06			// COMPARO CON 6
	BRNE	SALIDA_ALARMA_AUMENTO_MIN
	CLR		CONTADOR_M_D
SALIDA_ALARMA_AUMENTO_MIN:
	STS		MOD_MIN_U,	CONTADOR_M_U
	STS		MOD_MIN_D,	CONTADOR_M_D
	RET

AUMENTO_HORA_ALARMA:
	CPI		CONTADOR_H_D,	0x02
	BREQ	C_A_2_HORAS

	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x0A			// COMPARO CON 10
	BRNE	SALIDA_ALARMA_AUMENTO_HORA
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	C_A_D_HORAS

C_A_2_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x04			// COMPARO CON 4
	BRNE	SALIDA_ALARMA_AUMENTO_HORA
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	C_A_D_HORAS

C_A_D_HORAS:
	INC		CONTADOR_H_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_H_D,	0x03			// COMPARO CON 6
	BRNE	SALIDA_ALARMA_AUMENTO_HORA
	CLR		CONTADOR_H_D					// REINICIO CONTADOR DE DECENAS
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
SALIDA_ALARMA_AUMENTO_HORA:
	RET

DISMINUYE_MIN:
	RET

DISMINUYE_HORA:
	RET

DISMINUYE_DIA:
	RET

DISMINUYE_MES:
	RET

DISMINUYE_MIN_ALARMA:
	RET

DISMINUYE_HORA_ALARMA:
	RET
/****************************************/
// Interrupt routines
ISR_PCI1:
	PUSH	R16						// Store contents of R16 in stack
	IN		R16,	SREG			// Store SREG in R16
	PUSH	R16						// Store contents of R16 in stack

    SBIS	PINC,	PINC4
	INC		MODO
	CP		MODO,	MAX_MODES
	BRNE	CONTINUAR
	CLR		MODO
CONTINUAR:
	LDI		R16,	2
	CP		MODO,	R16
	BREQ	MOD_RELOJ
	LDI		R16,	3
	CP		MODO,	R16
	BREQ	MOD_FECHA
	LDI		R16,	4
	CP		MODO,	R16
	BREQ	S_ALARMA
MOD_RELOJ:
	LDI		R16,	0x01
	MOV		BANDERA_ACCION,	R16
	RJMP	EXIT_ISR_PCI1

MOD_FECHA:
	LDI		R16,	0x02
	MOV		BANDERA_ACCION,	R16
	RJMP	EXIT_ISR_PCI1

S_ALARMA:
	LDI		R16,	0x04
	MOV		BANDERA_ACCION,	R16
	RJMP	EXIT_ISR_PCI1
	
EXIT_ISR_PCI1:				// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES
	POP		R16						// Get contents from stack and store into R16
	OUT		SREG,	R16				// Load previous contents into SREG
	POP		R16						// Get contents from stack and store into R16
	RETI

ISR_TMR0_OVF:
	PUSH	R16
	IN		R16,	SREG
	PUSH	R16

	LDI		R16,	131						// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16						// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0

	LDI		R16,				0x00
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_1
	LDI		R16,				0x01
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_2
	LDI		R16,				0x02
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_3
	LDI		R16,				0x03
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_4

MULTI_DISPLAY_1:
	LDI		R16,		0x01
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_2:
	LDI		R16,		0x02
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_3:
	LDI		R16,		0x04
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_4:
	LDI		R16,		0x08
	MOV		S_PORT,		R16
	RJMP	FIN

FIN:
	LDI		R16,			0x03
	INC		CONTADOR_MULTI
	AND		CONTADOR_MULTI,	R16
	POP		R16
	OUT		SREG,	R16
	POP		R16
	RETI

ISR_TMR1_OVF:
	PUSH	R16
	IN		R16,	SREG
	PUSH	R16
	// ----------------------------------------------------------------------------------- //
	LDI		R16,	HIGH(TCNT1_value)
	STS		TCNT1H,	R16
	LDI		R16,	LOW(TCNT1_value)
	STS		TCNT1L,	R16
	// ----------------------------------------------------------------------------------- //
	LDI		ZL,		LOW(Cantidad_dias<<1)	// REINICIAMOS PUNTEROS DIAS
	LDI		ZH,		HIGH(Cantidad_dias<<1)
	ADD		ZL,		CONTADOR_MESES
	LPM		VARIABLE_DIAS,	Z
	// ----------------------------------------------------------------------------------- //
	//	LEER DE MEMORIA LOS VALORES DE MINUTOS, HORAS, DIAS Y MESES
	LDS		CONTADOR_M_U,		MOD_MIN_U	
	LDS		CONTADOR_M_D,		MOD_MIN_D
	LDS		CONTADOR_H_U,		MOD_HORA_U
	LDS		CONTADOR_H_D,		MOD_HORA_D
	LDS		CONTADOR_D_U,		MOD_DIA_U
	LDS		CONTADOR_D_D,		MOD_DIA_D
	LDS		CONTADOR_MES_U,		MOD_MES_U
	LDS		CONTADOR_MES_D,		MOD_MES_D
	// ----------------------------------------------------------------------------------- //
	LDI		R16,	0x01
	CP		BANDERA_ESTADO,	R16
	BRNE	REGRESO_1
	// ----------------------------------------------------------------------------------- //
	INC		CONTADOR_TIEMPO					// AUMENTA CONTADOR CADA 100 ms
	CPI		CONTADOR_TIEMPO,	100			// COMPARA CONTADOR CON 10 PARA HACER 1 SEG
	BRNE	REGRESO_1
	CLR		CONTADOR_TIEMPO					// REINICIO DE CONTADOR DE TIEMPO
	
	// ------------------------------------- minutos ------------------------------------- //
	INC		CONTADOR_M_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_M_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO_1
	CLR		CONTADOR_M_U

	INC		CONTADOR_M_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_M_D,	0x06			// COMPARO CON 6
	BRNE	REGRESO_1
	CLR		CONTADOR_M_D
	
	// ------------------------------------- HORAS --------------------------------------- //
	CPI		CONTADOR_H_D,	0x02
	BREQ	CONTEO_2_HORAS

CONTEO_1_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO_1
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	CONTEO_D_HORAS

CONTEO_2_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x04			// COMPARO CON 4
	BRNE	REGRESO_1
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	CONTEO_D_HORAS

CONTEO_D_HORAS:
	INC		CONTADOR_H_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_H_D,	0x03			// COMPARO CON 6
	BRNE	REGRESO_1
	CLR		CONTADOR_H_D					// REINICIO CONTADOR DE DECENAS
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	FECHA_TIMER
	
REGRESO_1:
	RJMP	REGRESO

FECHA_TIMER:
	// ------------------------------------- DIAS --------------------------------------- //
	CPI		CONTADOR_D_D,	0x03
	BREQ	CONTADOR_3_DIAS
	CPI		CONTADOR_D_D,	0x02
	BREQ	CONTADOR_2_DIAS

CONTADOR_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS

CONTADOR_2_DIAS:
	LDI		R16,	28
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_2_FEBRERO_DIAS
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	CONTEO_2_FEBRERO_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x09			// COMPARO CON 9
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS

CONTADOR_3_DIAS:
	LDI		R16,	31
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_3_1_DIAS
	LDI		R16,	30
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_3_2_DIAS
	CONTEO_3_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x02			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	CONTEO_3_2_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x01			// COMPARO CON 1
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	
CONTEO_D_DIAS:
	INC		CONTADOR_D_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_D_D,	0x04			// COMPARO CON 4
	BRNE	REGRESO
	CLR		CONTADOR_D_D
	LDI		CONTADOR_D_U,	0x01

	// ------------------------------------- MESES --------------------------------------- //
	CPI		CONTADOR_MES_D,	0x01
	BREQ	CONTADOR_2_MESES

CONTADOR_1_MESES:
	INC		CONTADOR_MESES
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO
	CLR		CONTADOR_MES_U	
	RJMP	CONTEO_D_MESES
CONTADOR_2_MESES:
	INC		CONTADOR_MESES
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x03			// COMPARO CON 2
	BRNE	REGRESO
	LDI		CONTADOR_MES_U,	0x01
	MOV		CONTADOR_MESES,	CONTADOR_MES_U
	RJMP	CONTEO_D_MESES

CONTEO_D_MESES:
	INC		CONTADOR_MES_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_MES_D,	0x02			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_MES_D
	LDI		CONTADOR_MES_U,	0x01
	CLR		CONTADOR_D_D
	LDI		CONTADOR_D_U,	0x01
	CLR		CONTADOR_H_D
	CLR		CONTADOR_H_U
	CLR		CONTADOR_M_D
	CLR		CONTADOR_M_U
REGRESO:
	// ----------------------------------------------------------------------------------- //
	// LEER DE MEMORIA LOS VALORES DE MINUTOS, HORAS, DIAS Y MESES
	STS		MOD_MIN_U,			CONTADOR_M_U
	STS		MOD_MIN_D,			CONTADOR_M_D
	STS		MOD_HORA_U,			CONTADOR_H_U
	STS		MOD_HORA_D,			CONTADOR_H_D
	STS		MOD_DIA_U,			CONTADOR_D_U
	STS		MOD_DIA_D,			CONTADOR_D_D
	STS		MOD_MES_U,			CONTADOR_MES_U
	STS		MOD_MES_D,			CONTADOR_MES_D
	// ----------------------------------------------------------------------------------- //
	POP		R16
	OUT		SREG,	R16
	POP		R16
	RETI
/****************************************/