/*
* Proyecto_Reloj.asm
*
* Creado: 2/27/2026 4:30:42 PM
* Autor : Josue Eli Mata Ixcayau
* Descripción: Un reloj digital que permita mostrar hora y minutos, dias y meses, tambien programar una alarma a una hora especifica.
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
.equ	TCNT1_value = 0xD8F0
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

.cseg
.org	0x0000
	JMP	START
.org	PCI1addr
	JMP	ISR_PCI1
.org	OVF1addr
	JMP	ISR_TMR1_OVF
.org	OVF0addr
	JMP	ISR_TMR0_OVF
.def	S_PORT =				R1
.def	CONTADOR_MULTI =		R2
.def	MODO =					R3
.def	ACCION =				R4
.def	CONTADOR_MODO =			R5
.def	MAX_MODES =				R6
.def	CONTADOR_MESES =		R7
.def	VARIABLE_DIAS =			R8
.def	REG_DISPLAY =			R14
.def	S_DISPLAY =				R15
.def	CONTADOR_M_U =			R17
.def	CONTADOR_M_D =			R18
.def	CONTADOR_H_U =			R19
.def	CONTADOR_H_D =			R20
.def	CONTADOR_TIEMPO =		R21
.def	CONTADOR_D_U =			R22
.def	CONTADOR_D_D =			R23
.def	CONTADOR_MES_U =		R24		
.def	CONTADOR_MES_D =		R25		

START:
 /****************************************/
// Configuración de la pila
	LDI     R16, LOW(RAMEND)
	OUT     SPL, R16
	LDI     R16, HIGH(RAMEND)
	OUT     SPH, R16
/****************************************/
// CREACION DE TABLA PARA DISPLAY
Numero: .db 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90, 0x88, 0x83, 0xF0, 0xA1, 0x86, 0x8E
Cantidad_dias:	.db	0x1F, 0x1C, 0x1F, 0x1E, 0x1F, 0x1E, 0x1F, 0x1F, 0x1E, 0x1F, 0x1E, 0x1F
/****************************************/
// Configuracion MCU
SETUP:
    CLI									// DESHABILITAR INTERRUPCIONES GLOBALES
	// PRESCALER
	LDI		R16,	(1 << CLKPCE)
	STS		CLKPR,	R16					// HABILITAR CAMBIOS EN CLOCK PRINCIPAL PARA HABILITAR PRESCALER
	LDI		R16,	(1 << CLKPS2)
	STS		CLKPR,	R16					// CAMBIAR FRECUENCIA DE 16 MHz a 1MHz

	// TIMER
	CALL INIT_TMR0
	CALL INIT_TMR1

    // ENTRADAS
	LDI		R16,	0xFF			
	OUT		DDRC,	R16					// PONER EN ENTRADAS LOS BITS 0 Y 1 DE PORTC
	LDI		R16,	0xFF				// VALOR PARA ACTIVAR PULL UPS EN 0 Y 1
	OUT		PORTC,	R16					// HABILITAR PULL UPS EN PINC

	// SALIDAS
	LDI		R16,	0xFF			
	OUT		DDRB,	R16					// PONER EN SALIDAS LOS BITS DE PORTB
	OUT		DDRD,	R16					// PONER EN SALIDAS LOS BITS DE PORTD  

	LDI		R16,	0xFF
	OUT		PORTB,	R16					// PONER DE VALOR INICIAL PARA PORTB 0

		// DISPLAYS DE 7 SEGMENTOS
	LDI		ZL,		LOW(Numero<<1)		//
	LDI		ZH,		HIGH(Numero<<1)		//
	LPM		R16,	Z
	OUT		PORTD,	R16					// PONER DE VALOR INICIAL PARA PORTD 0

	// HABILITACION DE INTERRUPCIONES
	LDI		R16,	(1 << PCIE1)
    STS		PCICR,	R16					// HABILITA INTERRUPCIONES EN PORTC
    LDI		R16,	(1 << PCINT8) | (1 << PCINT9) | (1 << PCINT10) | (1 << PCINT11) | (1 << PCINT12)
    STS		PCMSK1, R16
	LDI		R16,	(1 << TOIE0)
	STS		TIMSK0,	R16
	LDI		R16,	(1 << TOIE1)
	STS		TIMSK1,	R16

	// VARIABLES A USAR
	IN		R0,					PINC		// VALORES DE PIN C
	LDI		R16,				0x00
	MOV		CONTADOR_MULTI,		R16			// REINICIAR VALORES EN CONTADOR PARA MULTIPLEXADO
	LDI		R16,				5
	MOV		MAX_MODES,			R16
	CLR		CONTADOR_H_U					// REGISTRO DE CONTADOR
	CLR		CONTADOR_H_D					// REGISTRO DE CONTADOR
	CLR		CONTADOR_M_U					// CONTADOR DE UNIDADES PARA DISPLAY
	CLR		CONTADOR_M_D					// CONTADOR DE DECIMAS PARA DISPLAY
	CLR		CONTADOR_TIEMPO					// CONTADOR PARA TIEMPO
	CLR		REG_DISPLAY						// REGISTRO DONDE SE GUARDA VALOR QUE VA A SALIR A DISPLAY
	CLR		CONTADOR_D_U					
	CLR		CONTADOR_D_D					
	LDI		CONTADOR_MES_U,		0x01					
	CLR		CONTADOR_MES_D
	CLR		CONTADOR_MESES

	SEI									// HABILITAR INTERRUPCIONES GLOBALES
/****************************************/
// Loop Infinito
MAIN_LOOP:
	LDI		R16,	0
	CP		MODO,	R16
	BREQ	RELOJ
	LDI		R16,	1
	CP		MODO,	R16
	BREQ	FECHA
	LDI		R16,	2
	CP		MODO,	R16
	BREQ	MODIFICAR_RELOJ
	LDI		R16,	3
	CP		MODO,	R16
	BREQ	MODIFICAR_FECHA
	LDI		R16,	4
	CP		MODO,	R16
	BREQ	SET_ALARMA

	RELOJ:
	CALL	SALIDA_DISPLAY_HORA
	RJMP	REGRESO_MAIN
	FECHA:
	CALL	SALIDA_DISPLAY_FECHA
	RJMP	REGRESO_MAIN
	MODIFICAR_RELOJ:
	RJMP	REGRESO_MAIN
	MODIFICAR_FECHA:
	RJMP	REGRESO_MAIN
	SET_ALARMA:
	RJMP	REGRESO_MAIN
	REGRESO_MAIN:
    RJMP    MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines
INIT_TMR0:
	LDI		R16,	(1 << CS01)			// CONFIGURANDO PRESCALER DE I/O A 8
	OUT		TCCR0B,	R16
	LDI		R16,	131					// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16					// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0
	RET

INIT_TMR1:
	LDI		R16,	0x00
	STS		TCCR1A,	R16
	LDI		R16,	(1 << CS10)
	STS		TCCR1B,	R16
	LDI		R16,	HIGH(TCNT1_value)
	STS		TCNT1H,	R16
	LDI		R16,	LOW(TCNT1_value)
	STS		TCNT1L,	R16
	RET

SALIDA_DISPLAY_HORA:
	CLR		S_DISPLAY
	OUT		PORTB,		S_PORT				// MANDAMOS REGISTRO A PORTB

	SBRC	S_PORT,	0						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_M_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	1						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_M_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY
	
	SBRC	S_PORT,	2						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_H_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	3						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_H_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY

	LDI		ZL,		LOW(Numero<<1)			// REINICIAMOS PUNTEROS
	LDI		ZH,		HIGH(Numero<<1)			//
	ADD		ZL,		REG_DISPLAY				// SUMAMOS A PARTE BAJA DE PUNTERO CONTADOR DE DISPLAY
	LPM		S_DISPLAY,	Z					// MANDAMOS VALOR DE Z A REGISTRO DE SALIDA
	OUT		PORTD,	S_DISPLAY
	RET

SALIDA_DISPLAY_FECHA:
	CLR		S_DISPLAY
	OUT		PORTB,		S_PORT				// MANDAMOS REGISTRO A PORTB

	SBRC	S_PORT,	0						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_D_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	1						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_D_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY
	
	SBRC	S_PORT,	2						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_MES_U	// MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRC	S_PORT,	3						// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	CONTADOR_MES_D	// MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY

	LDI		ZL,		LOW(Numero<<1)			// REINICIAMOS PUNTEROS
	LDI		ZH,		HIGH(Numero<<1)			//
	ADD		ZL,		REG_DISPLAY				// SUMAMOS A PARTE BAJA DE PUNTERO CONTADOR DE DISPLAY
	LPM		S_DISPLAY,	Z					// MANDAMOS VALOR DE Z A REGISTRO DE SALIDA
	OUT		PORTD,	S_DISPLAY
	RET
/****************************************/
// Interrupt routines
ISR_PCI1:
	PUSH	R16						// Store contents of R16 in stack
	IN		R16,	SREG			// Store SREG in R16
	PUSH	R16						// Store contents of R16 in stack

    SBIS	PINC,	PINC4
	INC		MODO
	CP		MODO,	MAX_MODES
	BRNE	EXIT_ISR_PCI1
	CLR		MODO
	
	EXIT_ISR_PCI1:				// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES
	POP		R16						// Get contents from stack and store into R16
	OUT		SREG,	R16				// Load previous contents into SREG
	POP		R16						// Get contents from stack and store into R16
	RETI

ISR_TMR0_OVF:
	PUSH	R16
	IN		R16,	SREG
	PUSH	R16

	LDI		R16,	131						// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16						// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0

	LDI		R16,				0x00
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_1
	LDI		R16,				0x01
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_2
	LDI		R16,				0x02
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_3
	LDI		R16,				0x03
	CP		CONTADOR_MULTI,		R16
	BREQ	MULTI_DISPLAY_4

MULTI_DISPLAY_1:
	LDI		R16,		0x01
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_2:
	LDI		R16,		0x02
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_3:
	LDI		R16,		0x04
	MOV		S_PORT,		R16
	RJMP	FIN
MULTI_DISPLAY_4:
	LDI		R16,		0x08
	MOV		S_PORT,		R16
	RJMP	FIN

FIN:
	LDI		R16,			0x03
	INC		CONTADOR_MULTI
	AND		CONTADOR_MULTI,	R16
	POP		R16
	OUT		SREG,	R16
	POP		R16
	RETI

ISR_TMR1_OVF:
	PUSH	R16
	IN		R16,	SREG
	PUSH	R16
	// ----------------------------------------------------------------------------------- //
	LDI		R16,	HIGH(TCNT1_value)
	STS		TCNT1H,	R16
	LDI		R16,	LOW(TCNT1_value)
	STS		TCNT1L,	R16
	// ----------------------------------------------------------------------------------- //
	LDI		YL,		LOW(Cantidad_dias<<1)	// REINICIAMOS PUNTEROS DIAS
	LDI		YH,		HIGH(Cantidad_dias<<1)
	ADD		YL,		CONTADOR_MESES
	LPM		VARIABLE_DIAS,	Z
	// ----------------------------------------------------------------------------------- //
	INC		CONTADOR_TIEMPO					// AUMENTA CONTADOR CADA 100 ms
	CPI		CONTADOR_TIEMPO,	100			// COMPARA CONTADOR CON 10 PARA HACER 1 SEG
	BRNE	REGRESO_1
	CLR		CONTADOR_TIEMPO					// REINICIO DE CONTADOR DE TIEMPO
	
	// ------------------------------------- MINUTOS ------------------------------------- //
	INC		CONTADOR_M_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_M_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO_1
	CLR		CONTADOR_M_U

	INC		CONTADOR_M_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_M_D,	0x06			// COMPARO CON 6
	BRNE	REGRESO_1
	CLR		CONTADOR_M_D
	
	// ------------------------------------- HORAS --------------------------------------- //
	CPI		CONTADOR_H_D,	0x02
	BREQ	CONTEO_2_HORAS

CONTEO_1_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO_1
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	CONTEO_D_HORAS

CONTEO_2_HORAS:
	INC		CONTADOR_H_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_H_U,	0x04			// COMPARO CON 4
	BRNE	REGRESO_1
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	RJMP	CONTEO_D_HORAS
CONTEO_D_HORAS:
	INC		CONTADOR_H_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_H_D,	0x03			// COMPARO CON 6
	BRNE	REGRESO_1
	CLR		CONTADOR_H_D					// REINICIO CONTADOR DE DECENAS
	CLR		CONTADOR_H_U					// REINICIO CONTADOR DE UNIDADES
	
REGRESO_1:
	RJMP	REGRESO
	// ------------------------------------- DIAS --------------------------------------- //
	CPI		CONTADOR_D_D,	0x03
	BREQ	CONTADOR_3_DIAS
	CPI		CONTADOR_D_D,	0x02
	BREQ	CONTADOR_2_DIAS

CONTADOR_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS

CONTADOR_2_DIAS:
	LDI		R16,	28
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_2_FEBRERO_DIAS
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x0A			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	CONTEO_2_FEBRERO_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x09			// COMPARO CON 1
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS

CONTADOR_3_DIAS:
	LDI		R16,	31
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_3_1_DIAS
	LDI		R16,	30
	CP		VARIABLE_DIAS,	R16
	BREQ	CONTEO_3_2_DIAS
	CONTEO_3_1_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x02			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	CONTEO_3_2_DIAS:
	INC		CONTADOR_D_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_D_U,	0x01			// COMPARO CON 1
	BRNE	REGRESO
	CLR		CONTADOR_D_U
	RJMP	CONTEO_D_DIAS
	

CONTEO_D_DIAS:
	INC		CONTADOR_D_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_D_D,	0x04			// COMPARO CON 4
	BRNE	REGRESO
	CLR		CONTADOR_D_D
	LDI		CONTADOR_D_U,	0x01
	
	// ------------------------------------- MESES --------------------------------------- //
	CPI		CONTADOR_MES_D,	0x01
	BREQ	CONTADOR_2_MESES

CONTADOR_1_MESES:
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x0A			// COMPARO CON 10
	BRNE	REGRESO
	LDI		CONTADOR_MES_U,	0x01
	RJMP	CONTEO_D_MESES
CONTADOR_2_MESES:
	INC		CONTADOR_MES_U					// AUMENTO VALOR DE UNIDADES
	CPI		CONTADOR_MES_U,	0x03			// COMPARO CON 2
	BRNE	REGRESO
	LDI		CONTADOR_MES_U,	0x01
	RJMP	CONTEO_D_MESES

CONTEO_D_MESES:
	INC		CONTADOR_MES_D					// AUMENTO VALOR DE DECENAS
	CPI		CONTADOR_MES_D,	0x02			// COMPARO CON 2
	BRNE	REGRESO
	CLR		CONTADOR_MES_D
	LDI		CONTADOR_MES_U,	0x01
	CLR		CONTADOR_D_D
	LDI		CONTADOR_D_U,	0x01
	CLR		CONTADOR_H_D
	CLR		CONTADOR_H_U
	CLR		CONTADOR_M_D
	CLR		CONTADOR_M_U
REGRESO:
	POP		R16
	OUT		SREG,	R16
	POP		R16
	RETI
/****************************************/