/*
* Laboratorio 3.asm
*
* Creado: 20 / 02 / 2026
* Autor : Josue Eli Mata Ixcayau
* Descripción: Contador de 4 bits con pushbuttons e interrupciones, contador de segundos en display de 7 
* segmentos
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

.cseg
.org	0x0000
	JMP		START
.org	PCI1addr
	JMP		ISR_PCI1
.org	OVF0addr
	JMP		ISR_TMR0_OVF
.def	CONTADOR =			R17
.def	DISPLAY_1 =			R18
.def	DISPLAY_2 =			R19
.def	CONTADOR_TIEMPO =	R20
.def	REG_DISPLAY =		R21
.def	S_DISPLAY =			R22
.def	V_DISPLAY =			R23
.def	COM_PORT =			R24
.def	S_PORT =			R25
 /****************************************/
// Configuración de la pila
START:
	LDI     R16,	LOW(RAMEND)
	OUT     SPL,	R16
	LDI     R16,	HIGH(RAMEND)
	OUT     SPH,	R16
/****************************************/
// CREACION DE TABLA PARA DISPLAY
Numero: .db 0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xF8, 0x80, 0x90, 0x88, 0x83, 0xF0, 0xA1, 0x86, 0x8E
// Configuracion MCU
SETUP:
	CLI								// DESHABILITAR INTERRUPCIONES GLOBALES
	// PRESCALER
	LDI		R16,	(1 << CLKPCE)
	STS		CLKPR,	R16				// HABILITAR CAMBIOS EN CLOCK PRINCIPAL PARA HABILITAR PRESCALER
	LDI		R16,	(1 << CLKPS2)
	STS		CLKPR,	R16				// CAMBIAR FRECUENCIA DE 16 MHz a 1MHz

	// TIMER
	LDI		R16,	(1 << CS01) | (1 << CS00) // CONFIGURANDO PRESCALER DE I/O A 64
	OUT		TCCR0B,	R16
	LDI		R16,	100				// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16				// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0

    // ENTRADAS
	LDI		R16,	0x03			
	OUT		DDRC,	R16				// PONER EN ENTRADAS LOS BITS 0 Y 1 DE PORTC
	LDI		R16,	0x03			// VALOR PARA ACTIVAR PULL UPS EN 0 Y 1
	OUT		PORTC,	R16				// HABILITAR PULL UPS EN PINC

	// SALIDAS
	LDI		R16,	0xFF			
	OUT		DDRB,	R16				// PONER EN SALIDAS LOS BITS DE PORTB
	OUT		DDRD,	R16				// PONER EN SALIDAS LOS BITS DE PORTD  

	LDI		R16,	0x00
	OUT		PORTB,	R16				// PONER DE VALOR INICIAL PARA PORTB 0

		// DISPLAYS DE 7 SEGMENTOS
	LDI		ZL,		LOW(Numero<<1)	//	
	LDI		ZH,		HIGH(Numero<<1)	//
	LPM		R16,	Z
	OUT		PORTD,	R16				// PONER DE VALOR INICIAL PARA PORTD 0

	// HABILITACION DE INTERRUPCIONES
	LDI		R16,	(1 << PCIE1)
    STS		PCICR,	R16				// HABILITA INTERRUPCIONES EN PORTC
    LDI		R16,	(1 << PCINT8) | (1 << PCINT9)
    STS		PCMSK1, R16
	LDI		R16,	(1 << TOIE0)
	STS		TIMSK0,	R16

	// VARIABLES A USAR
	IN		R6,			PINC		// VALORES DE PIN C
	LDI		CONTADOR,	0x00		// REGISTRO DE CONTADOR
	LDI		DISPLAY_1,	0x00		// CONTADOR DE UNIDADES PARA DISPLAY
	LDI		DISPLAY_2,	0x00		// CONTADOR DE DECIMAS PARA DISPLAY
	LDI		CONTADOR_TIEMPO,	0x00	// CONTADOR PARA TIEMPO
	LDI		REG_DISPLAY,	0x00	// REGISTRO DONDE SE GUARDA VALOR QUE VA A SALIR A DISPLAY
	LDI		V_DISPLAY,	0x01		// VALOR INICIAL PARA QUE COMIENCE EL XOR
	LDI		COM_PORT,	0x03		// VALOR INICIAL PARA QUE COMIENCE EL XOR

	SEI								// HABILITAR INTERRUPCIONES GLOBALES

/****************************************/
// Loop Infinito
MAIN_LOOP:
	RJMP    MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines
AUMENTO:
	INC		CONTADOR						// AUMENTA REGISTRO DE CONTADOR
	RET

DISMINUYE:
	DEC		CONTADOR						// DECREMENTA REGISTRO DE CONTADOR
	RET

BIT_0:
	SBRS	R16,	0				// SKIP IF BIT IN REGISTER IS SET
	CALL	AUMENTO
	RET

BIT_1:
	SBRS	R16,	1				// SKIP IF BIT IN REGISTER IS SET
	CALL	DISMINUYE
	RET

SALIDA_DISPLAY:
	EOR		V_DISPLAY,	COM_PORT	// XOR PARA VARIAR ENTRE 01 Y 10
	MOV		S_PORT,		V_DISPLAY	// MOVEMOS VALOR A REGISTRO DE SALIDA
	SWAP	S_PORT					// MOVEMOS BITS 0-3 A 4-7
	OR		S_PORT,		CONTADOR	// AGREGAMOS VALORES DE CONTADOR
	OUT		PORTB,		S_PORT		// MANDAMOS REGISTRO A PORTB

	SBRS	S_PORT,	4				// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	DISPLAY_1 // MOVER VALOR DE UNIDADES A REGISTRO DE DISPLAY

	SBRS	S_PORT,	5				// SKIP IF BIT IN REGISTER IS SET
	MOV		REG_DISPLAY,	DISPLAY_2 // MOVER VALOR DE DECENAS A REGISTRO DE DISPLAY

	LDI		ZL,		LOW(Numero<<1)	// REINICIAMOS PUNTEROS
	LDI		ZH,		HIGH(Numero<<1)	//
	ADD		ZL,		REG_DISPLAY		// SUMAMOS A PARTE BAJA DE PUNTERO CONTADOR DE DISPLAY
	LPM		S_DISPLAY,	Z			// MANDAMOS VALOR DE Z A REGISTRO DE SALIDA
	OUT		PORTD,	S_DISPLAY
	RET

/****************************************/
// Interrupt routines
ISR_PCI1:
	PUSH	R16						// Store contents of R16 in stack
	IN		R16,	SREG			// Store SREG in R16
	PUSH	R16						// Store contents of R16 in stack

    IN		R16,	PINC			// SE LEE EL PIN C
	MOV		R5,		R16				// MOVEMOS REGISTRO R16 A R5
	EOR		R5,		R6				// XOR ENTRE VALORES ACTUALES Y VALORES ANTERIORES
	MOV		R6,		R16				// MOVEMOS VALORES ACTUALES A VALORES ANTERIORES

	SBRC	R5,		0				// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_0
	SBRC	R5,		1				// SKIP IF BIT IN REGISTER IS CLEAR
	CALL	BIT_1
	
	ANDI	CONTADOR,	0x0F		// ELIMINA BITS MAS SIGNIFICANTIVOS
	OUT		PORTB,		CONTADOR	// SALIDA PARA PORTB

	POP		R16						// Get contents from stack and store into R16
	OUT		SREG,	R16				// Load previous contents into SREG
	POP		R16						// Get contents from stack and store into R16
	RETI

ISR_TMR0_OVF:
	PUSH	R16
	IN		R16,	SREG
	PUSH	R16

	LDI		R16,	100				// SE GUARDA EN R16 EL VALOR DE INICIO DEL TIMER
	OUT		TCNT0,	R16				// GUARDA VALORES INICIALES DE TIMER 0 EN TCNT0

	INC		CONTADOR_TIEMPO			// AUMENTA CONTADOR CADA 10 ms
	CPI		CONTADOR_TIEMPO,	100	// COMPARA CONTADOR CON 100
	BRNE	REGRESO	
	CLR		CONTADOR_TIEMPO			// REINICIO DE CONTADOR DE TIEMPO

	INC		DISPLAY_1				// AUMENTO VALOR DE UNIDADES
	CPI		DISPLAY_1,	0x0A		// COMPARO CON 10
	BRNE	REGRESO
	CLR		DISPLAY_1				// REINICIO CONTADOR DE UNIDADES

	INC		DISPLAY_2				// AUMENTO VALOR DE DECENAS
	CPI		DISPLAY_2,	0x06		// COMPARO CON 6
	BRNE	REGRESO
	CLR		DISPLAY_2				// REINICIO CONTADOR DE DECENAS
	CLR		DISPLAY_1				// REINICIO CONTADOR DE UNIDADES

REGRESO:
	CALL	SALIDA_DISPLAY
	POP		R16
	OUT		SREG,	R16
	POP		R16
	RETI
/****************************************/


