/*
* Prelaboratorio 1.asm
*
* Creado: 05 / 02 / 2026
* Autor : Josue Eli Mata Ixcayau
* Descripción: Pre laboratorio 1. Contador de 4 bits con 2 push buttons y 4 leds.
*/
/****************************************/
// Encabezado (Definición de Registros, Variables y Constantes)
.include "M328PDEF.inc"     // Include definitions specific to ATMega328P
.dseg
.org    SRAM_START
//variable_name:     .byte   1   // Memory alocation for variable_name:     .byte   (byte size)

.cseg
.org 0x0000
 /****************************************/
// Configuración de la pila
LDI     R16, LOW(RAMEND)
OUT     SPL, R16
LDI     R16, HIGH(RAMEND)
OUT     SPH, R16
/****************************************/
// Configuracion MCU
SETUP:
    // CONFIGURAR ENTRADAS Y SALIDAS
	// INPUT ----> PD5
	LDI		R16,	0x00
	OUT		DDRC,	R16		// PONIENDO EN 0 BITS 0 A 1 DE DDRC
	LDI		R16,	0xFF
	OUT		PORTC,	R16		// HABILITANDO PULL-UP PARA PC0 A PC7
	// OUTPUT ---> PB0
	LDI		R16,	0xFF
	OUT		DDRB,	R16		// PONIENDO EN 1 TODOS LOS BITS DE DDRB
	OUT		DDRD,	R16		// PONIENDO EN 1 TODOS LOS BITS DE DDRD
	LDI		R16,	0x00
	OUT		PORTB,	R16		// INICIALMENTE APAGADOS BITS DE PORTB
	OUT		PORTD,	R16		// INICIALMENTE APAGADOS BITS DE PORTB
	LDI		R16,	0x7F	// VALORES INICIALES DE PINC
	LDI		R20,	0x00	// CONTADOR_1
	LDI		R18,	0x00	// CONTADOR_1
	LDI		R22,	0x0F	
	MOV		R5,		R20
	MOV		R3,		R20

/****************************************/
// Loop Infinito
MAIN_LOOP:
    IN		R17,	PINC		// LEER PINC
	CP		R16,	R17			// COMPARA VALORES INICIALES CON VALORES ACTUALES
	BREQ	MAIN_LOOP			// SI SON IGUALES ENTONCES REGRESA, SALTA HASTA QUE NO SEAN IGUALES
	CALL	DELAY
	IN		R17,	PINC		// SE VUELVE A LEER PINC
	CP		R16,	R17			// SE COMPARA VALORES OTRA VEZ PARA VER SI NO HA CAMBIADO
	BREQ	MAIN_LOOP

	MOV		R2,	R17				// MOVEMOS LOS VALORES LEIDOS A OTRO REGISTRO
	EOR		R2,	R16				// SE HACE UN EXCLUSIVE OR ENTRE LOS REGISTROS LEIDOS Y LOS ANTIGUOS
								// PARA QUE EL RESULTADO SOLO PERMITA ACTUAR UNO DE LOS BOTONES
	SBRC	R2,	0				// SE COMPARA EL R2 PARA VER QUE BIT ESTA ENCENDIDO
	CALL	BIT_0				// LLAMA A LA FUNCION DE CADA BOTON
	
	SBRC	R2,	1
	CALL	BIT_1

	ANDI	R20,	0x0F		// SE HACE UNA COMPARACION CON 0x0F PARA QUE NO PASE DE 4 BITS
	MOV		R8,		R20

	SBRC	R2,	2
	CALL	BIT_2

	SBRC	R2,	3
	CALL	BIT_3

	OR		R8,	R18			// SE JUNTA LOS REGISTROS R20 Y R18 PARA JUNTAR LOS CONTADORES

	SBRC	R2,	4
	CALL	BIT_4

	OUT		PORTD, R8			// SE MUESTRA EN PORTD EL CONTADOR
	OUT		PORTB, R3			// SE MUESTRA EN PORTB LA SUMA
	MOV		R16,	R17			// SE MUEVEN LOS ULTIMOS VALORES DE ENTRADA AL REGISTRO DE ANTIGUOS
	RJMP    MAIN_LOOP

/****************************************/
// NON-Interrupt subroutines
DELAY:
	LDI		R19, 255		// VALORES INICIALES
	LDI		R21, 255

LOOP_DELAY_1:
	DEC		R19				// DECREMENTA
	BRNE	LOOP_DELAY_1	// SALTA HASTA QUE SEA IGUAL A 0

LOOP_DELAY_2:
	DEC		R21
	BRNE	LOOP_DELAY_1	// SALTA A DELAY 1 OTRA VEZ
	RET

AUMENTO_C1:					
	INC		R20
	RET

DISMINUYE_C1:
	DEC		R20
	RET

AUMENTO_C2:
	INC		R18
	ADD		R18,	R22		// DESPUES DE INCREMENTAR, SE SUMA 15 PARA QUE PASE A LOS BITS MAS SIGNIFICATIVOS
	ANDI	R18,	0xF0	// SE HACE UNA COMPARACION CON 0xF0 PARA QUE NO SE MUESTREN LOS 4 BITS MENOS SIGNIFICATIVOS
	RET

DISMINUYE_C2:
	DEC		R18				// DECREMENTA R18
	ANDI	R18,	0xF0	// BORRA LOS 3 BITS MENOS SIGNIFICATIVOS
	RET

SUMA:
	// MOVER CONTADOR 1
	MOV		R3, R20
	// MOVER CONTADOR 2
	MOV		R5, R18
	SWAP	R5
	AND		R5,	R22
	ADD		R3, R5
	RET

BIT_0:
	SBRS	R17,	 0			// SE REVISA SI EL PINC0 ESTA EN 1 PARA SALTAR LA SIGUIENTE LINEA
	CALL	AUMENTO_C1			// SI ESTA EN 0 SE INCREMENTA CONTADOR
	RET

BIT_1:
	SBRS	R17,	1			// SE REVISA SI EL PINC1 ESTA EN 1 PARA SALTAR LA SIGUIENTE LINEA
	CALL	DISMINUYE_C1		// SI ESTA EN 0 SE DECREMENTA CONTADOR
	RET

BIT_2:
	SBRS	R17,	2
	CALL	AUMENTO_C2
	RET
	
BIT_3:
	SBRS	R17,	3
	CALL	DISMINUYE_C2	
	RET

BIT_4:
	SBRS	R17,	4
	CALL	SUMA
	RET
/****************************************/
// Interrupt routines

/****************************************/


